runtime: python311 

instance_class: F1

env_variables:
  BUCKET_NAME: "up202203836"

handlers:
# Matches requests to /preditor/... to files in static/preditor/...
- url: /preditor
  static_dir: static/preditor

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
